"""Generate and install agent-runtime hook scripts.

The `recipes/` directory in the source tree ships reference hook
scripts, but it is not packaged into the wheel. This module embeds the
same scripts so that an installed `agentaudit` can scaffold them with
`agentaudit install-hook claude-code` — no repo checkout required.
"""

from __future__ import annotations

import json
import stat
from dataclasses import dataclass
from pathlib import Path

PRE_TOOL_USE_SCRIPT = """\
#!/usr/bin/env bash
# agentaudit / pre-tool-use.sh  (generated by `agentaudit install-hook`)
#
# Gates every Claude Code tool call through agentaudit's live blocker.
#   Exit 0 -> Claude Code proceeds with the tool call.
#   Exit 1 -> Claude Code refuses the call (agentaudit blocked it).
#   Exit 2 -> malformed input from the hook system; fail-closed.
#
# Tune via environment variables (all optional):
#   AGENTAUDIT_BUNDLED_SET    spec group to load (default: cli-safe)
#   AGENTAUDIT_BLOCK_SEVERITY minimum severity that blocks (default: high)
#   AGENTAUDIT_HISTORY        history JSONL path
#   AGENTAUDIT_LOG            decision-log JSONL path

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
HIST="${AGENTAUDIT_HISTORY:-${PROJECT_DIR}/.claude/agentaudit-history.jsonl}"
LOG="${AGENTAUDIT_LOG:-${PROJECT_DIR}/.claude/agentaudit-violations.jsonl}"
BUNDLED_SET="${AGENTAUDIT_BUNDLED_SET:-cli-safe}"
BLOCK_SEVERITY="${AGENTAUDIT_BLOCK_SEVERITY:-high}"

mkdir -p "$(dirname "${HIST}")" "$(dirname "${LOG}")"

exec agentaudit watch \\
    --mode hook \\
    --bundled-specs "${BUNDLED_SET}" \\
    --block-severity "${BLOCK_SEVERITY}" \\
    --history-file "${HIST}" \\
    --log-file "${LOG}"
"""


USER_PROMPT_SUBMIT_SCRIPT = """\
#!/usr/bin/env bash
# agentaudit / user-prompt-submit.sh  (generated by `agentaudit install-hook`)
#
# Companion to pre-tool-use.sh: records every user prompt into the same
# history file so consent-gated specs (pkg-install, runtime-config,
# instruction-file, destructive-shell) clear when the user approves an
# operation in chat. Without it, require_consent rules fail closed.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
HIST="${AGENTAUDIT_HISTORY:-${PROJECT_DIR}/.claude/agentaudit-history.jsonl}"

mkdir -p "$(dirname "${HIST}")"

exec agentaudit ingest \\
    --history-file "${HIST}" \\
    --actor user \\
    --event-kind message
"""


# (filename, script body, settings hook-event name, matcher-or-None)
_CLAUDE_CODE_HOOKS = (
    ("pre-tool-use.sh", PRE_TOOL_USE_SCRIPT, "PreToolUse", "*"),
    ("user-prompt-submit.sh", USER_PROMPT_SUBMIT_SCRIPT, "UserPromptSubmit", None),
)


@dataclass
class InstallResult:
    written: list[Path]
    skipped: list[Path]
    settings_path: Path
    settings_written: bool
    settings_snippet: str


def claude_code_settings_snippet() -> dict:
    """Return the `.claude/settings.json` hooks block for the scripts."""
    hooks: dict[str, list] = {}
    for filename, _body, event, matcher in _CLAUDE_CODE_HOOKS:
        entry: dict = {
            "hooks": [{"type": "command", "command": f".claude/hooks/{filename}"}]
        }
        if matcher is not None:
            entry = {"matcher": matcher, **entry}
        hooks.setdefault(event, []).append(entry)
    return {"hooks": hooks}


def _merge_settings(existing: dict, snippet: dict) -> tuple[dict, bool]:
    """Merge the hooks snippet into existing settings idempotently.

    Returns (merged, changed). An entry is only appended if no entry with
    the same command already exists under that event.
    """
    merged = dict(existing)
    hooks = dict(merged.get("hooks", {}))
    changed = False
    for event, entries in snippet["hooks"].items():
        current = list(hooks.get(event, []))
        existing_cmds = {
            h.get("command")
            for entry in current
            for h in entry.get("hooks", [])
        }
        for entry in entries:
            cmds = {h.get("command") for h in entry["hooks"]}
            if cmds & existing_cmds:
                continue
            current.append(entry)
            changed = True
        hooks[event] = current
    if changed:
        merged["hooks"] = hooks
    return merged, changed


def install_claude_code_hooks(
    project_dir: Path,
    *,
    force: bool = False,
    write_settings: bool = False,
) -> InstallResult:
    """Scaffold Claude Code hook scripts under `<project_dir>/.claude/hooks/`.

    Writes the two hook scripts (skipping existing ones unless `force`),
    makes them executable, and either merges the hooks block into
    `.claude/settings.json` (when `write_settings`) or leaves the snippet
    for the caller to print.
    """
    hooks_dir = project_dir / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    skipped: list[Path] = []
    for filename, body, _event, _matcher in _CLAUDE_CODE_HOOKS:
        dest = hooks_dir / filename
        if dest.exists() and not force:
            skipped.append(dest)
            continue
        dest.write_text(body, encoding="utf-8")
        dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        written.append(dest)

    snippet = claude_code_settings_snippet()
    settings_path = project_dir / ".claude" / "settings.json"
    settings_written = False
    if write_settings:
        existing: dict = {}
        if settings_path.exists():
            existing = json.loads(settings_path.read_text(encoding="utf-8"))
        merged, changed = _merge_settings(existing, snippet)
        if changed:
            settings_path.write_text(
                json.dumps(merged, indent=2) + "\n", encoding="utf-8"
            )
            settings_written = True

    return InstallResult(
        written=written,
        skipped=skipped,
        settings_path=settings_path,
        settings_written=settings_written,
        settings_snippet=json.dumps(snippet, indent=2),
    )
